### ISSUE TITLE
Sync list/export fails with "Invalid value for `object_type" error

### ISSUE THREAD

**Issue by vontresc** [delphix/dxm-toolkit#8]
Error occurred in dxmc v 0.4 and with Delphix Masking Engine version  5.3.2.0

I was trying to use the sync export and sync list on one of our projects and am getting the same error. It appears that the list function is returning  Profile_Expression objects that it cannot consume

EXCEPTION: Traceback (most recent call last):
  File "dxmc.py", line 22, in <module>
  File "click/core.py", line 764, in __call__
  File "click/core.py", line 717, in main
  File "click/core.py", line 1137, in invoke
  File "click/core.py", line 1137, in invoke
  File "click/core.py", line 956, in invoke
  File "click/core.py", line 555, in invoke
  File "click/decorators.py", line 64, in new_func
  File "click/core.py", line 555, in invoke
  File "dxm/dxm.py", line 2046, in list
  File "dxm/lib/DxSync/sync_worker.py", line 85, in sync_list
  File "dxm/lib/DxSync/sync_worker.py", line 148, in sync_worker
  File "dxm/lib/DxSync/DxSyncList.py", line 47, in __init__
  File "dxm/lib/DxSync/DxSyncList.py", line 89, in LoadSync
  File "dxm/lib/DxTools/DxTools.py", line 38, in paginator
  File "lib/python2.7/site-packages/masking_apis/apis/sync_api.py", line 396, in get_all_syncable_objects
  File "lib/python2.7/site-packages/masking_apis/apis/sync_api.py", line 477, in get_all_syncable_objects_with_http_info
  File "lib/python2.7/site-packages/masking_apis/api_client.py", line 323, in call_api
  File "lib/python2.7/site-packages/masking_apis/api_client.py", line 158, in __call_api
  File "lib/python2.7/site-packages/masking_apis/api_client.py", line 236, in deserialize
  File "lib/python2.7/site-packages/masking_apis/api_client.py", line 276, in __deserialize
  File "lib/python2.7/site-packages/masking_apis/api_client.py", line 627, in __deserialize_model
  File "lib/python2.7/site-packages/masking_apis/api_client.py", line 254, in __deserialize
  File "lib/python2.7/site-packages/masking_apis/api_client.py", line 276, in __deserialize
  File "lib/python2.7/site-packages/masking_apis/api_client.py", line 627, in __deserialize_model
  File "lib/python2.7/site-packages/masking_apis/models/export_object_metadata.py", line 96, in object_type
ValueError: Invalid value for `object_type` (PROFILE_EXPRESSION), must be one of ['ALGORITHM_REFERENCE', 'BINARYLOOKUP', 'CLEANSING', 'DATABASE_CONNECTOR', 'DATABASE_RULESET', 'DATE_SHIFT', 'DOMAIN', 'DOMAIN_REFERENCE', 'FILE_CONNECTOR', 'FILE_FORMAT', 'FILE_RULESET', 'GLOBAL_OBJECT', 'KEY', 'LOOKUP', 'MAPPLET', 'MASKING_JOB', 'MIN_MAX', 'SEGMENT', 'SOURCE_DATABASE_CONNECTOR', 'SOURCE_FILE_CONNECTOR', 'TOKENIZATION']

**Comment by vontresc** [comment]
Retested on 0.4.1, and the issue still occurrs

Peter

**Comment by pioro** [comment]
Hello,

Version 0.42 was build to support 5.3.2 Masking engine.

regards,
Marcin
